### PR TITLE
Text edits for the descriptions of each UX step

### PR DESCRIPTION
**Pull request by robashcom**
Hi. Hope this is useful. I do this kind of editing all the time for software/websites/professional bloggers. But I am really a UX designer and I appreciated your chart, so thought I'd give back. 

The #4 line correction is not very important. The rest are mostly fixing errors and are important. In a few places I have made two sentences out of one for clarity sake. 

-Rob

### CODE REVIEW

**Comment by sove** [comment]
That is SOOO much appreciated!

Have you got the chance to have a read on the text in the page itself?

Thanks a lot!

**Comment by robashcom** [comment]
You're welcome!

I edited the readme because it looked identical to the text inside the HTML. I wasn't sure how you wanted to copy and paste or if the text was served up from somewhere else. But my intent was that that text should show up in the chart.

Hope that clears it up.

-Rob

**Comment by robashcom** [comment]
Do you want me to fix the text in the HTML as well? The README txt was just
meant to be copied and pasted into the HTML. I can do it.

-Rob

On Fri, Mar 13, 2015 at 3:32 AM, Andrea <notifications@github.com> wrote:

> Merged #7 <https://github.com/uxchecklist/uxchecklist.github.io/pull/7>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uxchecklist/uxchecklist.github.io/pull/7#event-251782361>
> .
>



-- 
Rob Ashcom
http://robashcom.com/portfolio
http://www.linkedin.com/in/robashcom
408-439-1206

**Comment by sove** [comment]
Readme file meant to be the copy of in page text, so feel free to align them. I can't remember if I updated the Readme with latest change from the page.

Thanks!
PS: just crazy busy these weeks, I would have had a look at that in ages :/

**Comment by robashcom** [comment]
K. Will do. Business is crazy these days for me as well. Github is a quiet
place to escape to occasionally.

-Rob

On Tue, Mar 17, 2015 at 2:35 AM, Andrea <notifications@github.com> wrote:

> Readme file meant to be the copy of in page text, so feel free to align
> them. I can't remember if I updated the Readme with latest change from the
> page.
>
> Thanks!
> PS: just crazy busy these weeks, I would have had a look at that in ages :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uxchecklist/uxchecklist.github.io/pull/7#issuecomment-82243418>
> .
>



-- 
Rob Ashcom
http://robashcom.com/portfolio
http://www.linkedin.com/in/robashcom
408-439-1206

**Pull request merged**
