### PR TITLE
Handle multi-project in Google Drive, project share/rename and general improvements

### PR DESCRIPTION
**Pull request by alefranz**
Would be nice to improve the UI before accepting the PR.
Does anyone want to contribute?

### CODE REVIEW

**Comment by luzmcosta** [comment]
@alefranz  👋  What's going on here?  I see there's some UI help wanted.  Just the kind of thing I like to do. 😄

**Comment by sovesove** [comment]
Hey @luzmcosta we need to add some client-side functionality to manage multiple projects. We can chat more in details.

**Comment by alefranz** [comment]
Cool @sovesove !
Can you add a proper UI for the `Rename` functionality as well? :)

**Comment by luzmcosta** [comment]
@sovesove 👋  I just realized this message was here.  I'd love to chat.  You can [email me here](mailto:luzmcosta+uxchecklist@gmail.com) if that's more convenient than this stream.  I'm open to text, pseudo-code, sketches, skitches, snapshots of napkins in bars---whatever communicates the idea. 😊  TTYS

**Pull request merged**
