### PR TITLE
Adding Null Alt Text

### PR DESCRIPTION
**Pull request by mgifford**
basic accessibility. possibly some of these icons should be labeled, but at the very least they should have alt="".

### CODE REVIEW

**Comment by sovesove** [comment]
You are very much right sir, thank you.

**Comment by mgifford** [comment]
Just to be clear `alt="ico"` isn't meaningful.  what I had proposed `alt=""` means that the screen readers will ignore it. Good docs on this are here https://webaim.org/techniques/alttext/

**Comment by sovesove** [comment]
Oh thanks for sharing this as well, is pretty obvious accessibility is not on top of the list of my skills.
Thought something was better than nothing, rollback! :)

**Comment by mgifford** [comment]
If the alt text described the image and the image was more than decorative, then yes. In this case it is just eye candy though, so null is fine.

**Pull request merged**
